
import { Tool } from './types';

export const TOOLS_DATA: Tool[] = [
  // --- AI TOOLS ---
  { 
    id: "1", 
    name: "Cursor", 
    tool_type: "AI", 
    category: "Coding Assistance", 
    platform: ["Desktop"],
    is_ai_based: true,
    pricing: "Freemium", 
    rating_score: 4.9, 
    popularity_score: 4.8, 
    student_discount: true, 
    ease_of_use: 4.5, 
    skill_level: "intermediate", 
    website_url: "https://cursor.com", 
    description: "The AI-native code editor designed for pair programming with LLMs.",
    why_recommended: "Best-in-class integration of AI within the IDE workflow.",
    supported_formats: ["TS", "JS", "PY", "GO", "RUST"],
    download_location: "Desktop App (Win/Mac/Linux)"
  },
  { 
    id: "2", 
    name: "Midjourney", 
    tool_type: "AI", 
    category: "Image Generation", 
    platform: ["Web"],
    is_ai_based: true,
    pricing: "Paid", 
    rating_score: 4.8, 
    popularity_score: 4.9, 
    student_discount: false, 
    ease_of_use: 3.0, 
    skill_level: "intermediate", 
    website_url: "https://midjourney.com", 
    description: "State-of-the-art text-to-image generation.",
    why_recommended: "Unmatched artistic quality and detail in generated imagery.",
    supported_formats: ["PNG", "JPG", "WEBP"],
    download_location: "Discord / Web"
  },
  { 
    id: "3", 
    name: "Claude 3.5 Sonnet", 
    tool_type: "AI", 
    category: "Research Tools", 
    platform: ["Web", "iOS", "Android"],
    is_ai_based: true,
    pricing: "Freemium", 
    rating_score: 4.9, 
    popularity_score: 4.7, 
    student_discount: false, 
    ease_of_use: 4.8, 
    skill_level: "beginner", 
    website_url: "https://claude.ai", 
    description: "Advanced reasoning model with exceptional coding capabilities.",
    why_recommended: "Superior reasoning and more human-like writing compared to peers.",
    supported_formats: ["PDF", "TXT", "CSV", "JSON"],
    download_location: "Web / Mobile App"
  },
  { 
    id: "7", 
    name: "Perplexity", 
    tool_type: "AI", 
    category: "Research Tools", 
    platform: ["Web", "iOS", "Android"],
    is_ai_based: true,
    pricing: "Freemium", 
    rating_score: 4.9, 
    popularity_score: 4.8, 
    student_discount: true, 
    ease_of_use: 5.0, 
    skill_level: "beginner", 
    website_url: "https://perplexity.ai", 
    description: "AI search engine providing cited answers to complex questions.",
    why_recommended: "Real-time web access with transparent source citations.",
    supported_formats: ["WEB", "PDF"],
    download_location: "Web / Mobile App"
  },

  // --- UNIVERSAL UTILITIES (Non-AI Focus) ---
  { 
    id: "u1", 
    name: "ILovePDF", 
    tool_type: "Utility", 
    category: "File Optimization", 
    platform: ["Web", "Desktop"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 4.7, 
    popularity_score: 4.9, 
    student_discount: false, 
    ease_of_use: 5.0, 
    skill_level: "beginner", 
    website_url: "https://ilovepdf.com", 
    description: "Every tool you need to use PDFs, at your fingertips. All are 100% FREE and easy to use!", 
    security_rating: 9.0, 
    is_best_for_students: true,
    why_recommended: "Comprehensive suite of PDF tools without registration.",
    supported_formats: ["PDF", "DOCX", "JPG", "PNG"],
    download_location: "Web / Desktop"
  },
  { 
    id: "u2", 
    name: "TinyPNG", 
    tool_type: "Utility", 
    category: "File Optimization", 
    platform: ["Web"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 4.9, 
    popularity_score: 5.0, 
    student_discount: false, 
    ease_of_use: 5.0, 
    skill_level: "beginner", 
    website_url: "https://tinypng.com", 
    description: "Smart WebP, PNG and JPEG compression. Optimize your images with a perfect balance in quality and file size.", 
    security_rating: 9.5, 
    is_best_for_students: true,
    why_recommended: "Best-in-class lossy compression for web images.",
    supported_formats: ["PNG", "JPG", "WEBP"],
    download_location: "Web API / Web"
  },
  { 
    id: "u3", 
    name: "CloudConvert", 
    tool_type: "Utility", 
    category: "File Conversion", 
    platform: ["Web"],
    is_ai_based: false,
    pricing: "Freemium", 
    rating_score: 4.8, 
    popularity_score: 4.7, 
    student_discount: false, 
    ease_of_use: 4.8, 
    skill_level: "beginner", 
    website_url: "https://cloudconvert.com", 
    description: "Convert nearly any audio, video, document, ebook, archive, image, spreadsheet, or presentation format.", 
    security_rating: 9.2, 
    is_best_for_students: true,
    why_recommended: "Supports 200+ formats with high-quality conversions.",
    supported_formats: ["200+ formats"],
    download_location: "Web"
  },
  { 
    id: "u4", 
    name: "Handbrake", 
    tool_type: "Software", 
    category: "File Optimization", 
    platform: ["Desktop"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 4.9, 
    popularity_score: 4.5, 
    student_discount: false, 
    ease_of_use: 3.5, 
    skill_level: "advanced", 
    website_url: "https://handbrake.fr", 
    description: "The open source video transcoder. Convert video from nearly any format to a selection of modern, widely supported codecs.", 
    security_rating: 10.0,
    why_recommended: "Industry standard for open-source video transcoding.",
    supported_formats: ["MP4", "MKV", "WEBM"],
    download_location: "Desktop App"
  },
  { 
    id: "u5", 
    name: "OBS Studio", 
    tool_type: "Software", 
    category: "Video Editing", 
    platform: ["Desktop"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 4.9, 
    popularity_score: 4.9, 
    student_discount: false, 
    ease_of_use: 3.0, 
    skill_level: "advanced", 
    website_url: "https://obsproject.com", 
    description: "Free and open source software for video recording and live streaming.", 
    security_rating: 10.0,
    why_recommended: "Powerful, free, and highly customizable streaming software.",
    supported_formats: ["FLV", "MP4", "MOV"],
    download_location: "Desktop App"
  },
  { 
    id: "u6", 
    name: "Photopea", 
    tool_type: "Utility", 
    category: "Design Utilities", 
    platform: ["Web"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 4.8, 
    popularity_score: 4.6, 
    student_discount: false, 
    ease_of_use: 4.2, 
    skill_level: "intermediate", 
    website_url: "https://photopea.com", 
    description: "Advanced photo editor in your browser. A free alternative to Adobe Photoshop.", 
    is_best_for_students: true,
    why_recommended: "Full Photoshop-like features in a browser for free.",
    supported_formats: ["PSD", "AI", "XD", "PDF"],
    download_location: "Web"
  },
  { 
    id: "u7", 
    name: "SmallPDF", 
    tool_type: "Utility", 
    category: "File Optimization", 
    platform: ["Web", "iOS", "Android"],
    is_ai_based: false,
    pricing: "Freemium", 
    rating_score: 4.6, 
    popularity_score: 4.8, 
    student_discount: true, 
    ease_of_use: 4.9, 
    skill_level: "beginner", 
    website_url: "https://smallpdf.com", 
    description: "The platform that makes it super easy to convert and edit all your PDF files.", 
    is_best_for_students: true,
    why_recommended: "User-friendly interface for quick PDF tasks.",
    supported_formats: ["PDF", "PPT", "XLS", "JPG"],
    download_location: "Web / Mobile"
  },
  { 
    id: "u8", 
    name: "FFmpeg", 
    tool_type: "Software", 
    category: "File Conversion", 
    platform: ["Desktop"],
    is_ai_based: false,
    pricing: "Free", 
    rating_score: 5.0, 
    popularity_score: 4.4, 
    student_discount: false, 
    ease_of_use: 1.0, 
    skill_level: "advanced", 
    website_url: "https://ffmpeg.org", 
    description: "A complete, cross-platform solution to record, convert and stream audio and video.", 
    security_rating: 10.0,
    why_recommended: "The ultimate command-line tool for audio/video processing.",
    supported_formats: ["All formats"],
    download_location: "CLI Tool"
  }
];
